name: kmb_app
description: "Kokrajhar Municipal Board"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7
  intl: ^0.19.0

  jwt_decoder: ^2.0.1
  http: ^1.6.0
  flutter_otp_kit: ^3.1.0
  connectivity_plus: ^7.0.0
  package_info_plus: ^9.0.0

  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  go_router: ^17.0.1

  hive_flutter: ^1.1.0
  hive: 2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter_launcher_icons:
  color: "#FF708CD6"
  android: true
  ios: true
  image_path: "assets/icons/logo_black.png"
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    # - assets/fonts/

